[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quoll"
version = "0.0.1"
dependencies = [
    "jpype1==0.7.5",
    "pims==0.4.1",
    "matplotlib",
    "miplib",
    "mrcfile",
    "notebook",
    "numpy",
    "pandas",
    "scikit-image",
    "scipy",
    "tifffile>2021",
]
authors = [
    {name="Elaine Ho", email="elaine.ho@rfi.ac.uk"}
]
description = "Image quality assessment for electron tomography"
readme = "README.md"
license = {file="LICENSE"}
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["*"]  # package names should match these glob patterns (["*"] by default)
exclude = ["tests"]  # exclude packages matching these glob patterns (empty by default)

[project.urls]
"Homepage" = "https://github.com/rosalindfranklininstitute/quoll"
"Bug Tracker" = "https://github.com/rosalindfranklininstitute/quoll/issues"

[project.scripts] 
oneimgfrc = "quoll.ui.frc_oneimg_ui:oneimgfrc"